# Generated by Django 3.2 on 2021-04-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('Course_Number', models.IntegerField(default='example: 1')),
                ('Instructor_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Duration', models.FloatField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
